# Generated by Django 3.2 on 2021-04-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
